# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/youssef/ISIMA/Infographie/tp1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/youssef/ISIMA/Infographie/tp1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/youssef/ISIMA/Infographie/tp1/CMakeFiles /home/youssef/ISIMA/Infographie/tp1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/youssef/ISIMA/Infographie/tp1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named archiDemo

# Build rule for target.
archiDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 archiDemo
.PHONY : archiDemo

# fast build rule for target.
archiDemo/fast:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/build
.PHONY : archiDemo/fast

Camera.o: Camera.cpp.o

.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i

.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s

.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

DisplayManager.o: DisplayManager.cpp.o

.PHONY : DisplayManager.o

# target to build an object file
DisplayManager.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/DisplayManager.cpp.o
.PHONY : DisplayManager.cpp.o

DisplayManager.i: DisplayManager.cpp.i

.PHONY : DisplayManager.i

# target to preprocess a source file
DisplayManager.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/DisplayManager.cpp.i
.PHONY : DisplayManager.cpp.i

DisplayManager.s: DisplayManager.cpp.s

.PHONY : DisplayManager.s

# target to generate assembly for a file
DisplayManager.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/DisplayManager.cpp.s
.PHONY : DisplayManager.cpp.s

EventController.o: EventController.cpp.o

.PHONY : EventController.o

# target to build an object file
EventController.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/EventController.cpp.o
.PHONY : EventController.cpp.o

EventController.i: EventController.cpp.i

.PHONY : EventController.i

# target to preprocess a source file
EventController.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/EventController.cpp.i
.PHONY : EventController.cpp.i

EventController.s: EventController.cpp.s

.PHONY : EventController.s

# target to generate assembly for a file
EventController.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/EventController.cpp.s
.PHONY : EventController.cpp.s

FramesData.o: FramesData.cpp.o

.PHONY : FramesData.o

# target to build an object file
FramesData.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/FramesData.cpp.o
.PHONY : FramesData.cpp.o

FramesData.i: FramesData.cpp.i

.PHONY : FramesData.i

# target to preprocess a source file
FramesData.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/FramesData.cpp.i
.PHONY : FramesData.cpp.i

FramesData.s: FramesData.cpp.s

.PHONY : FramesData.s

# target to generate assembly for a file
FramesData.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/FramesData.cpp.s
.PHONY : FramesData.cpp.s

GeometricTransform.o: GeometricTransform.cpp.o

.PHONY : GeometricTransform.o

# target to build an object file
GeometricTransform.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/GeometricTransform.cpp.o
.PHONY : GeometricTransform.cpp.o

GeometricTransform.i: GeometricTransform.cpp.i

.PHONY : GeometricTransform.i

# target to preprocess a source file
GeometricTransform.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/GeometricTransform.cpp.i
.PHONY : GeometricTransform.cpp.i

GeometricTransform.s: GeometricTransform.cpp.s

.PHONY : GeometricTransform.s

# target to generate assembly for a file
GeometricTransform.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/GeometricTransform.cpp.s
.PHONY : GeometricTransform.cpp.s

MainApplication.o: MainApplication.cpp.o

.PHONY : MainApplication.o

# target to build an object file
MainApplication.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/MainApplication.cpp.o
.PHONY : MainApplication.cpp.o

MainApplication.i: MainApplication.cpp.i

.PHONY : MainApplication.i

# target to preprocess a source file
MainApplication.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/MainApplication.cpp.i
.PHONY : MainApplication.cpp.i

MainApplication.s: MainApplication.cpp.s

.PHONY : MainApplication.s

# target to generate assembly for a file
MainApplication.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/MainApplication.cpp.s
.PHONY : MainApplication.cpp.s

Modele.o: Modele.cpp.o

.PHONY : Modele.o

# target to build an object file
Modele.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/Modele.cpp.o
.PHONY : Modele.cpp.o

Modele.i: Modele.cpp.i

.PHONY : Modele.i

# target to preprocess a source file
Modele.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/Modele.cpp.i
.PHONY : Modele.cpp.i

Modele.s: Modele.cpp.s

.PHONY : Modele.s

# target to generate assembly for a file
Modele.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/Modele.cpp.s
.PHONY : Modele.cpp.s

MouseData.o: MouseData.cpp.o

.PHONY : MouseData.o

# target to build an object file
MouseData.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/MouseData.cpp.o
.PHONY : MouseData.cpp.o

MouseData.i: MouseData.cpp.i

.PHONY : MouseData.i

# target to preprocess a source file
MouseData.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/MouseData.cpp.i
.PHONY : MouseData.cpp.i

MouseData.s: MouseData.cpp.s

.PHONY : MouseData.s

# target to generate assembly for a file
MouseData.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/MouseData.cpp.s
.PHONY : MouseData.cpp.s

RenderingGlobalRoutines.o: RenderingGlobalRoutines.cpp.o

.PHONY : RenderingGlobalRoutines.o

# target to build an object file
RenderingGlobalRoutines.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/RenderingGlobalRoutines.cpp.o
.PHONY : RenderingGlobalRoutines.cpp.o

RenderingGlobalRoutines.i: RenderingGlobalRoutines.cpp.i

.PHONY : RenderingGlobalRoutines.i

# target to preprocess a source file
RenderingGlobalRoutines.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/RenderingGlobalRoutines.cpp.i
.PHONY : RenderingGlobalRoutines.cpp.i

RenderingGlobalRoutines.s: RenderingGlobalRoutines.cpp.s

.PHONY : RenderingGlobalRoutines.s

# target to generate assembly for a file
RenderingGlobalRoutines.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/RenderingGlobalRoutines.cpp.s
.PHONY : RenderingGlobalRoutines.cpp.s

WindowManager.o: WindowManager.cpp.o

.PHONY : WindowManager.o

# target to build an object file
WindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/WindowManager.cpp.o
.PHONY : WindowManager.cpp.o

WindowManager.i: WindowManager.cpp.i

.PHONY : WindowManager.i

# target to preprocess a source file
WindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/WindowManager.cpp.i
.PHONY : WindowManager.cpp.i

WindowManager.s: WindowManager.cpp.s

.PHONY : WindowManager.s

# target to generate assembly for a file
WindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/WindowManager.cpp.s
.PHONY : WindowManager.cpp.s

WrapperSDL.o: WrapperSDL.cpp.o

.PHONY : WrapperSDL.o

# target to build an object file
WrapperSDL.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/WrapperSDL.cpp.o
.PHONY : WrapperSDL.cpp.o

WrapperSDL.i: WrapperSDL.cpp.i

.PHONY : WrapperSDL.i

# target to preprocess a source file
WrapperSDL.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/WrapperSDL.cpp.i
.PHONY : WrapperSDL.cpp.i

WrapperSDL.s: WrapperSDL.cpp.s

.PHONY : WrapperSDL.s

# target to generate assembly for a file
WrapperSDL.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/WrapperSDL.cpp.s
.PHONY : WrapperSDL.cpp.s

abstractCamera.o: abstractCamera.cpp.o

.PHONY : abstractCamera.o

# target to build an object file
abstractCamera.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/abstractCamera.cpp.o
.PHONY : abstractCamera.cpp.o

abstractCamera.i: abstractCamera.cpp.i

.PHONY : abstractCamera.i

# target to preprocess a source file
abstractCamera.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/abstractCamera.cpp.i
.PHONY : abstractCamera.cpp.i

abstractCamera.s: abstractCamera.cpp.s

.PHONY : abstractCamera.s

# target to generate assembly for a file
abstractCamera.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/abstractCamera.cpp.s
.PHONY : abstractCamera.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/archiDemo.dir/build.make CMakeFiles/archiDemo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... archiDemo"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... DisplayManager.o"
	@echo "... DisplayManager.i"
	@echo "... DisplayManager.s"
	@echo "... EventController.o"
	@echo "... EventController.i"
	@echo "... EventController.s"
	@echo "... FramesData.o"
	@echo "... FramesData.i"
	@echo "... FramesData.s"
	@echo "... GeometricTransform.o"
	@echo "... GeometricTransform.i"
	@echo "... GeometricTransform.s"
	@echo "... MainApplication.o"
	@echo "... MainApplication.i"
	@echo "... MainApplication.s"
	@echo "... Modele.o"
	@echo "... Modele.i"
	@echo "... Modele.s"
	@echo "... MouseData.o"
	@echo "... MouseData.i"
	@echo "... MouseData.s"
	@echo "... RenderingGlobalRoutines.o"
	@echo "... RenderingGlobalRoutines.i"
	@echo "... RenderingGlobalRoutines.s"
	@echo "... WindowManager.o"
	@echo "... WindowManager.i"
	@echo "... WindowManager.s"
	@echo "... WrapperSDL.o"
	@echo "... WrapperSDL.i"
	@echo "... WrapperSDL.s"
	@echo "... abstractCamera.o"
	@echo "... abstractCamera.i"
	@echo "... abstractCamera.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

